export {default as Login } from './Login'
export {default as HomeLayout} from './HomeLayout'
export {default as Error} from './Error'
export {default as ForgotPassword} from './ForgotPassword'
export {default as ResetPassword} from './ResetPassword'
export {default as Landing} from './Landing'
export {default as SingleAdmin} from './SingleAdmin'
export {default as ServiceAreaManager} from './ServiceAreaManager'
export {default as BusinessTypeManager} from './BusinessTypeManager'